#!/usr/bin/env node
// new-spec.mjs
//
// Scaffolds a new Playwright spec file in tests/ from a flow name.
// The skeleton enforces the repository conventions:
//   - data-testid selectors only
//   - one happy path + one negative path
//   - Page Object Models referenced (created separately)
//
// Usage:
//   node scripts/new-spec.mjs <flow-name-kebab-case>
//
// Example:
//   node scripts/new-spec.mjs enroll-form-validation
//
// Writes:
//   tests/<flow-name>.spec.js
//
// Exit codes:
//   0 - spec written
//   1 - flow name missing or already exists

import { mkdir, writeFile, access } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const flow = process.argv[2];

if (!flow || !/^[a-z][a-z0-9-]*$/.test(flow)) {
  console.error('Usage: node scripts/new-spec.mjs <flow-name-kebab-case>');
  console.error('Example: node scripts/new-spec.mjs enroll-form-validation');
  process.exit(1);
}

const TESTS_DIR = resolve(process.cwd(), 'tests');
const SPEC_PATH = resolve(TESTS_DIR, `${flow}.spec.js`);

async function fileExists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function describeFromFlow(flow) {
  return flow.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

const SKELETON = `// tests/${flow}.spec.js
// Covers: ${describeFromFlow(flow)}
//
// Generated by .claude/skills/playwright-spec-generator/scripts/new-spec.mjs
// Conventions enforced:
//   - data-testid selectors ONLY (see reference/selector-rules.md)
//   - one happy path + at least one negative path
//   - Page Objects under tests/pages/ when the flow spans multiple pages
//
// After editing, run:
//   cd app && npx playwright test ../tests/${flow}.spec.js --reporter=list

const { test, expect } = require('@playwright/test');

test.describe('${describeFromFlow(flow)}', () => {
  test('happy path: <state the user outcome>', async ({ page }) => {
    await page.goto('/');
    // TODO: drive the flow via data-testid selectors.
    // Example:
    //   await page.getByTestId('enroll-claude-code-pro').click();
    //   await page.getByTestId('full-name-input').fill('Tim Warner');
    //   await page.getByTestId('submit-enroll').click();
    //   await expect(page).toHaveURL(/confirm\\.html$/);
    //   await expect(page.getByTestId('confirm-name')).toHaveText('Tim Warner');
    throw new Error('TODO: implement happy path');
  });

  test('negative path: <state what should be rejected>', async ({ page }) => {
    await page.goto('/');
    // TODO: drive the flow into a known-bad state and assert the
    // user-visible error. Use data-testid for the error banner.
    throw new Error('TODO: implement negative path');
  });
});
`;

async function main() {
  await mkdir(dirname(SPEC_PATH), { recursive: true });
  if (await fileExists(SPEC_PATH)) {
    console.error(`new-spec: refusing to overwrite ${SPEC_PATH}`);
    process.exit(1);
  }
  await writeFile(SPEC_PATH, SKELETON, 'utf8');
  console.log(`Wrote ${SPEC_PATH}`);
  console.log(``);
  console.log(`Next steps:`);
  console.log(`  1. Replace TODO comments with real flow drivers.`);
  console.log(`  2. cd app && npx playwright test ../tests/${flow}.spec.js`);
  console.log(`  3. Hand off to qa-reviewer subagent for review.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
